version: '3.9'
services:
  kong:
    image: kong:latest
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
    volumes:
      - ./kong.yml:/etc/kong/kong.yml

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=paisasense
    ports:
      - "3306:3306"
